---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_width: 7
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(magrittr)
library(ggplot2)
library(tidyr)
library(dplyr)
library(wrswoR.benchmark)
```


```{r}
sub_correctness <-
wrswoR.benchmark::correctness %>%
  filter(r * n == j) %>%
  tbl_df

STEPS <- sqrt(length(unique(sub_correctness$i)))
stopifnot(STEPS == trunc(STEPS))

sub_correctness_means <-
  sub_correctness %>%
  group_by(prob, j, R) %>%
  summarize(R.Freq = n() / STEPS) %>%
  ungroup %>%
  rename(item = R)
```

```{r}
sub_correctness %>%
  tidyr::gather(algo, item, ccrank, crank, rank, rej, expj, expjs, R) %>%
  group_by(i %% STEPS, algo, j, prob, item) %>%
  summarize(item.Freq = n()) %>%
  ungroup %>%
  left_join(sub_correctness_means) %>%
  group_by(j, prob) %>%
  do(plot={
    ggplot(., aes(x=factor(item), y=item.Freq, color=algo)) +
      geom_violin() +
      facet_grid(j~prob)
  }) %>%
  magrittr::extract2("plot")
```
